import { FLUX_OPEN_ID_CONNECT_AUTHENTICATION_BACKEND_DEFAULT_FRONTEND_BASE_ROUTE } from "../FluxOpenIdConnectAuthenticationBackend/FLUX_OPEN_ID_CONNECT_AUTHENTICATION_BACKEND.mjs";
import { PROTOCOL_HTTP } from "../../../flux-http-api/src/Protocol/PROTOCOL.mjs";

export const FLUX_OPEN_ID_CONNECT_AUTHENTICATION_BACKEND_PROXY_AUTHENTICATION_BACKEND_DEFAULT_BASE_ROUTE = FLUX_OPEN_ID_CONNECT_AUTHENTICATION_BACKEND_DEFAULT_FRONTEND_BASE_ROUTE;

export const FLUX_OPEN_ID_CONNECT_AUTHENTICATION_BACKEND_PROXY_AUTHENTICATION_BACKEND_DEFAULT_URL = `${PROTOCOL_HTTP}://flux-open-id-connect-authentication-backend`;
